### ISSUE TITLE
Resolve typing issue in main.start()

### ISSUE THREAD

**Issue by KatieProchilo** [Joll59/d-ser-t#11]
In `main.start()`, after `service.batchTranscribe().then()`, `results` is currently cast as `any`:
```
const results: any = service.resultArray.map( . . . )
```

We should resolve this typing issue or decide it's truly necessary.

**Comment by Joll59** [comment]
actually @KatieProchilo you addressed this in one of your refactors. 
[Creating an Object inLine here](https://github.com/Joll59/d-ser-t/blob/5a18aa84ff2c785d3e796825091151486776b941/src/main.ts#L89)

We can remove `any` from all code above this point. 

It does however create a new `any` issue down the line: 
helper Function `calculateSER` needs a type for it argument. 

PR to address this will follow.

**Comment by Joll59** [comment]
fixed with #24
