### ISSUE TITLE
Convert d-ser-t to a Mocha test

### ISSUE THREAD

**Issue by KatieProchilo** [Joll59/d-ser-t#18]
d-ser-t needs to be converted into a mocha test so it can easier be integrated in to a CI pipeline. 

If the accuracy is less than a certain threshold, the test should fail. The issue is currently is the tool outputting the results to the console, but you'd need post processing of the data with another script before you can mark the pipeline as successful. 

This inefficiency can be avoided if we simply use a Mocha test.

**Comment by Joll59** [comment]
interim output for d-ser-t for CI pipeline: boolean. @Joll59 / @KatieProchilo  pair to implement changes @HobbyProjects

**Comment by Joll59** [comment]
fixed with #41
